### ISSUE TITLE
Still want to be involved?

### ISSUE THREAD

**Issue by cobratbq** [otr4j/otr4j#73]
Hi @ibauersachs, do you still want to be involved in this org? Should I remove you? (If you don't care at all, there is little point in keeping you in.)

**Comment by ibauersachs** [comment]
No. But I still think it's a shame that the projects had to split.

**Comment by cobratbq** [comment]
> No. But I still think it's a shame that the projects had to split.

Well, it didn't have to. The refactoring that I did had multiple purposes, one of which was to carefully look at the code-base and fix issues and mitigate risks. Trying to _merge_ this code now would be an exercise in futility.

**Comment by cobratbq** [comment]
@ibauersachs My point isn't to push you away. I just find it hard to get any reading on the sentiment, also w.r.t. the jitsi (desktop) contributions, so I ask. Let's keep it as-is.

**Comment by ibauersachs** [comment]
> > No. But I still think it's a shame that the projects had to split.
> 
> Well, it didn't have to. The refactoring that I did had multiple purposes, one of which was to carefully look at the code-base and fix issues and mitigate risks. Trying to _merge_ this code now would be an exercise in futility.

I remember a licensing issue.

Anyway, I don't really mind either way. Jitsi Desktop is mostly dead, except for the part that is still used by Jigasi. Anything else there is just for... fun? In case you want to introduce OTR v4 there, feel free to do so. I'm not dismissing your PR there either, I'm investigating some stuff and will look at it. However, I'm neither working often nor long at it.

**Comment by cobratbq** [comment]
On July 11, 2023 9:10:55 PM UTC, Ingo Bauersachs ***@***.***> wrote:
>> > No. But I still think it's a shame that the projects had to split.
>> 
>> Well, it didn't have to. The refactoring that I did had multiple purposes, one of which was to carefully look at the code-base and fix issues and mitigate risks. Trying to _merge_ this code now would be an exercise in futility.
>
>I remember a licensing issue.

Correct.

>
>Anyway, I don't really mind either way. Jitsi Desktop is mostly dead, except for the part that is still used by Jigasi. Anything else there is just for... fun?

Yeah, so my impression was mostly correct. It's why I asked about it.

> In case you want to introduce OTR v4 there, feel free to do so.

It's in a branch of my jitsi fork. It's mostly a prototype to see things working.

> I'm not dismissing your PR there either, I'm investigating some stuff and will look at it. However, I'm neither working often nor long at it.

Okay. Dismissing is IMO a valid option. LMK if time is an issue.

**Comment by cobratbq** [comment]
On July 11, 2023 9:10:55 PM UTC, Ingo Bauersachs ***@***.***> wrote:
>[..] I remember a licensing issue.

Actually, what licensing issue did you have in mind? You guys changed the license at some later time. Is that what you mean?

**Comment by ibauersachs** [comment]
> Actually, what licensing issue did you have in mind? You guys changed the license at some later time. Is that what you mean?

I don't remember the timeline nor the specifics. I think it involved the CLA, Apache 2 vs. LGPL and contribution not under the CLA. That was during Atlassian, I actually don't know how 8x8 is handling this now.

**Comment by cobratbq** [comment]
On July 19, 2023 5:24:38 PM UTC, Ingo Bauersachs ***@***.***> wrote:
>> Actually, what licensing issue did you have in mind? You guys changed the license at some later time. Is that what you mean?
>
>I don't remember the timeline nor the specifics. I think it involved the CLA, Apache 2 vs. LGPL and contribution not under the CLA. That was during Atlassian, I actually don't know how 8x8 is handling this now.

Well, in short. The project was forked, not by me. I started contributing (jitsi/otr4j got little to no attention) but was one of few interested. I used it for clean up, fix some dubious code (also committed to jitsi/otr4j) and larger general improvements. Jitsi team changed the license for their otr4j. I continued my work on fork, in particular with design that better protects from mistakes.

I know not everyone thrilled about the fork, but I think it was done in good spirit and meant to be picked up as a common effort. I supported it because otr4j got little to no attention and this would provide a more independent character and lower threshold to contributing.

Now license in fork is still original, and there are a few commits that I do not have ownership over, so I cannot offer it back. In addition, the design is *massively* overhauled. (And of course OTRv4.)

**Comment by cobratbq** [comment]
To add to the above for completeness:
- I invited gpolitis to the github org, but he had not accepted.
- And, mostly for other readers: my earlier contributions were discussed on the mailinglist, but are stil [visible in Discourse](<https://community.jitsi.org/t/jitsi-dev-fragmentation-support-pushed-to-otr4j-jitsi-soon/8102>) ([list of topics](<https://community.jitsi.org/u/danny_van_heumen/activity/topics>))
